baseURL = "https://readymix.bangunan.co/"
languageCode = "id"
title = "Readymix Beton | Pemasok Readymix Beton Curah Truk Molen"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Readymix Beton - Layanan supply pengecoran dengan truk molen, kualitas beton terbaik untuk cor bangunan dengan harga terjangkau dan pengiriman cepat."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual readymix beton", "beton truk molen", "pemasok beton cor", "beton kualitas terbaik", "readymix harga terjangkau", "beton curah"]
  base_price = 900000
  price_range = 200000
  free_shipping = true
  materials = [
  "Readymix Kelas B0",
  "Readymix Kelas K225",
  "Readymix Kelas K250",
  "Readymix Kelas K300",
  "Readymix Kelas K350"
  ]
  categories = ["Readymix Beton", "Material Bangunan", "Beton Curah"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Pengiriman"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa dikembalikan dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika kualitas beton tidak sesuai spesifikasi.",
  "Pengembalian gratis untuk produk yang tidak sesuai pesanan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Layanan Readymix Beton Berkualitas"
  hero_description = "Kami menyediakan jasa pengecoran readymix beton dengan truk molen untuk berbagai kebutuhan konstruksi. Solusi ideal untuk proyek pembangunan dengan beton berkualitas tinggi dan proses pengecoran yang efisien."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Readymix"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menawarkan readymix beton berkualitas tinggi dengan berbagai pilihan mutu untuk memenuhi kebutuhan konstruksi Anda. Layanan pengiriman cepat dan konsultasi gratis untuk memastikan beton sesuai dengan spesifikasi proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "readymix.bangunan.co menyediakan layanan pengecoran readymix beton dengan truk molen, melayani berbagai proyek konstruksi dari skala kecil hingga besar. Kami menjamin beton yang kami tawarkan berkualitas tinggi, dengan harga bersaing dan pengiriman tepat waktu. Pilih kami untuk memastikan proyek pengecoran Anda berjalan lancar dengan hasil terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya {menggunakan|memanfaatkan|memakai} layanan readymix beton dari readymix.bangunan.co untuk {proyek|pembangunan|konstruksi} rumah saya, dan hasilnya {sangat memuaskan|luar biasa|menakjubkan}. Beton yang {disediakan|dikirim|diberikan} {berkualitas tinggi|bermutu|premium} dan proses pengecorannya {sangat rapi|tertata|berjalan lancar}.|Layanan readymix beton dari readymix.bangunan.co {membantu saya|memenuhi kebutuhan saya|sangat membantu} dalam proyek rumah saya. Beton yang {disediakan|dikirim} {berkualitas|bermutu|premium} dan proses pengecorannya {rapi|lancar|bersih}.}"
  response = "{Terima kasih atas {kepercayaan|dukungan|pilihan} Anda! Kami senang dapat {menyediakan|menghadirkan|memenuhi} readymix beton {berkualitas|premium|bermutu tinggi} untuk {proyek|pembangunan} Anda.|Kami {sangat menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih telah memilih readymix beton kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{readymix.bangunan.co {sangat membantu|mempermudah|mengarahkan} dalam memenuhi kebutuhan beton untuk proyek saya. Produk yang {saya pesan|saya terima|dikirim} {berkualitas|bermutu|sesuai standar} dan sesuai dengan {spesifikasi|kebutuhan|persyaratan} yang {dibutuhkan|diharapkan}.|Saya terbantu oleh readymix.bangunan.co dalam memenuhi kebutuhan beton saya. Produknya {berkualitas|bermutu tinggi|premium} dan sesuai dengan {spesifikasi|kebutuhan} proyek.}"
  response = "{Kami sangat menghargai ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan layanan readymix dari kami.|Terima kasih atas {ulasan|masukan} Anda! Kami {gembira|senang} Anda puas dengan layanan dan produk kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bambang|Hadi|Tono|Gilang|Bayu|Faisal|Rizal|Ali|Ahmad}"
  message = "{Layanan readymix beton dari readymix.bangunan.co {sangat cepat|efisien|responsif} dan {berkualitas|tepat waktu|bermutu}. Beton yang {disediakan|dikirim} sesuai dengan {kualitas|standar|spesifikasi} yang saya harapkan untuk proyek {perumahan|real estate|properti} saya.|Beton dari readymix.bangunan.co {cepat dikirim|tepat waktu|sesuai harapan} dan {berkualitas|bermutu|cocok untuk} proyek perumahan saya.}"
  response = "{Terima kasih! Kami {berkomitmen|fokus|dedikasi} untuk menyediakan layanan readymix beton berkualitas dengan {pengiriman|waktu pengiriman|proses} yang {tepat waktu|efisien|lancar}.|Kami {apresiasi|menghargai} ulasan Anda. Terima kasih atas {kepercayaan|pilihan} Anda menggunakan readymix beton kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Bayu|Fajar|Hendra|Dian|Rizky|Yoga|Yudi|Ari|Gani}"
  message = "{Saya {sangat puas|senang|terkesan} dengan layanan readymix beton dari readymix.bangunan.co. Beton yang kami gunakan {sangat kuat|kokoh|berkualitas tinggi} dan sesuai dengan kebutuhan {proyek|pembangunan|konstruksi} kami.|Beton readymix dari readymix.bangunan.co {sangat kuat|kokoh|berkualitas} dan cocok untuk proyek kami. Layanannya juga {memuaskan|berkualitas|tepat}.}"
  response = "{Senang mendengar Anda puas dengan {beton|layanan} readymix kami. Terima kasih atas {kepercayaannya|pilihannya|dukungan Anda}!|Kami {bahagia|senang|gembira} Anda puas dengan layanan dan produk kami. Terima kasih atas {kepercayaannya|dukungan Anda}!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan readymix.bangunan.co {sangat memuaskan|luar biasa|baik sekali}. Produk beton yang {saya pesan|dikirim} {berkualitas tinggi|bermutu|premium} dan sesuai dengan {harapan|ekspektasi|spesifikasi saya}.|Saya sangat puas dengan {produk|layanan} readymix.bangunan.co. Beton yang {saya pesan|dikirim} {berkualitas tinggi|premium|bermutu} dan {sesuai dengan harapan|memenuhi ekspektasi|sesuai standar}.}"
  response = "{Terima kasih! Kami senang dapat {membantu|mewujudkan|melayani} proyek pengecoran Anda dengan {beton|produk} terbaik.|Kami menghargai {ulasan|masukan} Anda. Terima kasih telah {memilih|mempercayai|menggunakan} readymix beton kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Agus|Dedi|Toni|Yanto|Wawan|Benny|Rio|Iwan|Galih}"
  message = "{Beton readymix dari readymix.bangunan.co {sangat sesuai|tepat|cocok} dengan {spesifikasi|standar|kebutuhan} proyek {jalan raya|infrastruktur|komersial} yang saya kerjakan. Pengirimannya {cepat|tepat waktu|aman} dan {lancar|terorganisir|sesuai jadwal}.|Saya puas dengan {produk|beton} readymix untuk proyek jalan yang saya kerjakan. Pengirimannya {cepat|tepat waktu|lancar} dan {sesuai harapan|memenuhi ekspektasi|aman}.}"
  response = "{Kami {senang|bahagia|gembira} mendengar bahwa Anda puas dengan {produk|layanan} kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {mempercayai|memilih|menggunakan} readymix beton kami. Kami {senang|gembira} Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Readymix Kelas B0"
  price = "870.000 /m3"
[[params.tabelItems]]
  name = "Readymix Kelas K225"
  price = "640.000 /m3"
[[params.tabelItems]]
  name = "Readymix Kelas K250"
  price = "860.000 /m3"
[[params.tabelItems]]
  name = "Readymix Kelas K300"
  price = "900.000 /m3"
[[params.tabelItems]]
  name = "Readymix Kelas K350"
  price = "940.000 /m3"

[params.appliList]
  "Readymix Kelas B0" = "pondasi, lantai dasar"
  "Readymix Kelas K225" = "dinding, kolom struktural"
  "Readymix Kelas K250" = "lantai bangunan, jalan ringan"
  "Readymix Kelas K300" = "jalan raya, konstruksi berat"
  "Readymix Kelas K350" = "jembatan, gedung bertingkat"

[params.kegunaanList]
  "Readymix Kelas B0" = "digunakan untuk pondasi dan pekerjaan dasar"
  "Readymix Kelas K225" = "cocok untuk konstruksi dinding dan kolom struktural"
  "Readymix Kelas K250" = "digunakan untuk lantai bangunan dan jalan ringan"
  "Readymix Kelas K300" = "digunakan untuk konstruksi jalan raya dan bangunan berat"
  "Readymix Kelas K350" = "cocok untuk konstruksi jembatan dan gedung bertingkat"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Layanan Pengecoran Readymix Beton | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"